(function() {

  var LSS_MISSIONKEYWORD_STORAGE = "LSS_MISSIONKEYWORD_STORAGE";

  function setSettings() {

    I18n.translations.de.lssm.missionKeywordDefaults = {
      name: 'Einsatzstichworte',
      settingsName: 'Einsatzstichworte - Einstellungen',
      domain: 'leitstellenspiel.de',
      fw: 'B',
      thl: 'THL',
      abc: 'ABC',
      rd: 'RD',
      ktp: 'KTP',
      pol: 'POL',
      thw: 'THW',
      bp: 'BP',
      bma: 'BMA',
      sek: 'SEK',
      mek: 'MEK',
      bmaLong: 'Brandmeldeanlage',
      show: "Ein-/Ausblenden",
      keywords: {
        0: 'Mülleimerbrand',
        1: 'Containerbrand',
        2: 'Brennender PKW',
        3: 'Motorrad-Brand',
        4: 'Brennendes Gras',
        5: 'Zimmerbrand',
        6: 'Gartenlaubenbrand',
        7: 'Brennendes Laub',
        8: 'Sperrmüllbrand',
        9: 'Strohballen Brand',
        10: 'Traktor Brand',
        11: 'Brennende Telefonzelle',
        12: 'Baum auf Straße',
        13: 'Brennender LKW',
        14: 'Kleiner Feldbrand',
        15: 'Kleiner Waldbrand',
        16: 'Wohnwagenbrand',
        17: 'Brand in Briefkasten',
        18: 'Brennendes Gebüsch',
        19: 'Brennender Anhänger',
        20: 'Kellerbrand',
        21: 'Schornsteinbrand',
        22: 'Dachstuhlbrand',
        23: 'Fettbrand in Pommesbude',
        24: 'Brennendes Bus-Häuschen',
        25: 'Verkehrsunfall',
        26: 'Brand im Supermarkt',
        27: 'Auffahrunfall',
        28: 'Garagenbrand',
        29: 'Maschinenbrand',
        30: 'Große Ölspur',
        31: 'Auslaufende Betriebsstoffe',
        32: 'Kaminbrand',
        33: 'Mähdrescher Brand',
        34: 'Brand im Supermarkt',
        35: 'Feuer im Krankenhaus',
        36: 'Brennender Güterwaggon',
        37: 'Mülleimerbrand',
        38: 'Mülleimerbrand',
        39: 'Mülleimerbrand',
        40: 'Mülleimerbrand',
        41: 'Großbrand',
        42: 'Tankstellenbrand',
        43: 'Massenkarambolage',
        44: 'Alkoholintoxikation',
        45: 'Nasenbluten unstillbar',
        46: 'Herzinfarkt',
        47: 'akuter Asthma-Anfall',
        48: 'Krampfanfall',
        49: 'Fieber',
        50: 'Gestürzte Person',
        51: 'Brand in Werkstatt',
        52: 'Brand auf Weihnachtsmarkt',
        53: 'Verkehrsunfall durch Glatteis',
        54: 'Personenschaden durch Verbrennung',
        55: 'Brennender Tannenbaum',
        56: 'Betrunkene Person auf Weihnachtsmarkt',
        57: 'Gestürzter Fußgänger',
        58: 'Gestürzter Radfahrer',
        59: 'Gefahrgutunfall',
        60: 'Ladendiebstahl',
        61: 'Ladendiebstahl',
        62: 'Parkendes Auto gerammt',
        63: 'Parkendes Auto gerammt',
        64: 'Metalldiebstahl',
        65: 'Taschendiebstahl',
        66: 'Notebook aus Schule entwendet',
        67: 'Personalienaufnahme von Schwarzfahrer',
        68: 'Personalienaufnahme von Schwarzfahrer',
        69: 'Personalienaufnahme von Schwarzfahrer',
        70: 'Personalienaufnahme von Schwarzfahrer',
        71: 'Parkendes Auto gerammt',
        72: 'Bewusstloser Kranführer',
        73: 'Schlägerei',
        74: 'Randalierende Person',
        75: 'Unangemeldete Demonstration',
        76: 'Küchenbrand',
        77: 'Person hinter Tür',
        78: 'Kleintier in Not',
        79: 'Verletzte Person auf Baugerüst',
        80: 'Rauchentwicklung in Museum',
        81: 'Einbruch in Keller',
        82: 'Einbruch in Wohnung',
        83: 'Gefahrgut-LKW verunglückt',
        84: 'Brennende Lok',
        85: 'Sachbeschädigung',
        86: 'Sporthallenbrand',
        87: 'Kleinflugzeug abgestürzt',
        88: 'Brennender Bollerwagen',
        89: 'LKW Auffahrunfall',
        90: 'Ruhestörung',
        91: 'Keller unter Wasser',
        92: 'Schlaganfall',
        93: 'Brennender Bus',
        94: 'Kleine Ölspur',
        95: 'Ausgedehnte Ölspur',
        96: 'Feuer in Schnellrestaurant',
        97: 'Aufgerissener Öltank',
        98: 'Angefahrene Person',
        99: 'Flugzeug abgestürzt',
        100: 'Küchenbrand',
        101: 'Zimmerbrand',
        102: 'Feuer in Einfamilienhaus',
        103: 'Feuer in Einfamilienhaus',
        104: 'Feuer in Einfamilienhaus',
        105: 'Feuer in Einfamilienhaus',
        106: 'Massenschlägerei',
        107: 'Massenschlägerei',
        108: 'Schwangere in Notsituation',
        109: 'Beginnende Geburt',
        110: 'Vaginale Blutung',
        111: 'Brennende Vogelscheuche',
        112: 'Brennendes Kürbisfeld',
        113: 'Kürbissuppe übergekocht',
        114: 'Hexe hängt in Baum',
        115: 'Zombiebiss',
        116: 'Monster ausgebrochen',
        117: 'Kürbisse geklaut',
        118: 'Frankenstein gesichtet',
        119: 'Süßigkeitendiebstahl',
        120: 'LKW umgestürzt',
        121: 'LKW umgestürzt',
        122: 'Motorradunfall',
        123: 'Verkehrsunfall',
        124: 'Verkehrsunfall',
        125: 'Verkehrsunfall',
        126: 'Verkehrsunfall',
        127: 'Verkehrsunfall',
        128: 'Auffahrunfall',
        129: 'Brennender Adventskranz',
        130: 'Rangelei auf Weihnachtsmarkt',
        131: 'Mittlerer Feldbrand',
        132: 'Großer Feldbrand',
        133: 'Großer Feldbrand',
        134: 'Großer Waldbrand',
        135: 'Großer Waldbrand',
        136: 'Großfeuer im Wald',
        137: 'Großfeuer im Wald',
        138: 'Flächenbrand',
        139: 'Flächenbrand',
        140: 'Flächenbrand',
        141: 'Flächenbrand',
        142: 'Feuer auf Balkon',
        143: 'Brennende Papiercontainer',
        144: 'Brennende Hecke',
        145: 'Trunkenheitsfahrt',
        146: 'Brennendes Reetdachhaus',
        147: 'Krankentransport',
        148: 'Ampelausfall',
        149: 'Pannenfahrzeug',
        150: 'Hausfriedensbruch',
        151: 'Raub',
        152: 'Häusliche Gewalt',
        153: 'Hilflose Person',
        154: 'Hilflose Person',
        155: 'Akuter Harnstau',
        156: 'Harnleiter Blutung',
        157: 'Herzrhythmusstörungen',
        158: 'Tiefgarage unter Wasser',
        159: 'Äste auf Fahrbahn',
        160: 'Umherfliegendes Baumaterial',
        161: 'Baum auf PKW',
        162: 'Baum auf PKW',
        163: 'Baum auf Dach',
        164: 'Kopfplatzwunde',
        165: 'Gehirnerschütterung',
        166: 'Fassadenteile drohen zu fallen',
        167: 'Beschädigter Dachbereich',
        168: 'Baum auf Gleisen',
        169: 'Baum auf Gleisen',
        170: 'Baum auf Gleisen',
        171: 'Parkdeck voll Wasser gelaufen',
        172: 'Straße unter Wasser',
        173: 'Straße unter Wasser',
        174: 'Erdrutsch',
        175: 'Erdrutsch',
        176: 'LKW in Hauswand',
        177: 'Eingestürztes Wohnhaus',
        178: 'Gefahrgut-LKW verunglückt',
        179: 'Schädelverletzung',
        180: 'Wirbelsäulenverletzung',
        181: 'Sturz aus Höhe',
        182: 'Sturz aus Höhe',
        183: 'Sonnenstich',
        184: 'Hitzschlag',
        185: 'Hitzekrampf',
        186: 'Lagerhallenbrand',
        187: 'Feuer im Lagerraum',
        188: 'Personenkontrolle',
        189: 'Verkehrsbehinderung',
        190: 'Diebstahl aus Kfz',
        191: 'Baum auf Radweg',
        192: 'Brennende Trafostation',
        193: 'Brennende Trafostation',
        194: 'Person unter Baum eingeklemmt',
        195: 'Schwerpunkteinsatz Tageswohnungseinbrüche',
        196: 'Schwerpunkteinsatz Verkehrsüberwachung',
        197: 'Präsenzeinsatz Volksfest',
        198: 'Jugendschutzkontrolle in Diskothek',
        199: 'Geländedurchsuchung nach Beweismittel',
        200: 'Geplante Razzia',
        201: 'Fußball Bundesliga-Spiel',
        202: 'Diebstahl auf Weihnachtsmarkt',
        203: 'Brennende Weihnachtsmarktbude',
        204: 'Scheunenbrand',
        205: 'Feuer auf Bauernhof - Mittel',
        206: 'Feuer auf Bauernhof - Groß',
        207: 'Gefahrgutunfall - Groß',
        208: 'Leck in Chemikalientank',
        209: 'Fahrraddiebstahl',
        210: 'Unfall mit Motorsäge',
        211: 'Unterzuckerung',
        212: 'Akute Bauchschmerzen',
        213: 'Gasexplosion',
        214: 'Bürobrand',
        215: 'Chlorgasaustritt',
        216: 'Brennender Bollerwagen',
        217: 'Brennender Bollerwagen',
        218: 'Brennender Bollerwagen',
        219: 'Brennender Bollerwagen',
        220: 'Brennender Bollerwagen',
        221: 'Zugunglück (Groß)',
        222: 'Zugunglück (Klein)',
        223: 'Brandsicherheitswache bei Volksfest',
        224: 'Brandsicherheitswachdienst im Theater',
        225: 'Dorf/Stadtfest',
        226: 'Volkslauf',
        227: 'Angemeldete Demonstration',
        228: 'Absicherung Musikumzug',
        229: 'Absicherung Radrennen',
        230: 'Feuerprobealarm an Schule',
        231: 'Entflohener Gefangener',
        232: 'Kabeldiebstahl',
        233: 'Suche nach Vermissten',
        234: 'Entschärfung von Weltkriegsbombe',
        235: 'Verletzte Person auf Hochspannungsmast',
        236: 'Verletzte Person auf Hochspannungsmast',
        237: 'Verkehrsunfall mit Zug',
        238: 'Verkehrsunfall mit Linienbus',
        239: 'Verkehrsunfall mit Linienbus',
        240: 'Gasgeruch',
        241: 'Wildunfall',
        242: 'Pfefferspray in Schule',
        243: 'Reitunfall mit Pkw',
        244: 'Person in Wasser',
        245: 'Person in Wasser',
        246: 'Person in Wasser',
        247: 'Pkw in Wasser',
        248: 'LKW in Wasser',
        249: 'Bus in Wasser',
        250: 'Person in Wasser',
        251: 'Person in Wasser',
        252: 'Person in Wasser',
        253: 'Pkw in Wasser',
        254: 'LKW in Wasser',
        255: 'Bus in Wasser',
        256: 'Zusammenstoß zweier Boote',
        257: 'Verkehrsüberwachung',
        258: 'Baumaschine umgestürzt',
        259: 'Brennender PKW durch Feuerwerkskörper',
        260: 'Sperrmüllbrand durch Feuerwerkskörper',
        261: 'Kleiner Feldbrand durch Feuerwerkskörper',
        262: 'Kellerbrand durch Feuerwerkskörper',
        263: 'Brennendes Bus-Häuschen durch Feuerwerkskörper',
        264: 'Feuer auf Balkon durch Feuerwerkskörper',
        265: 'Brennende Papiercontainer durch Feuerwerkskörper',
        266: 'Brennende Hecke durch Feuerwerkskörper',
        267: 'Trunkenheitsfahrt nach Silvesterparty',
        268: 'Brennendes Reetdachhaus durch Feuerwerkskörper',
        269: 'Kfz durch Feuerwerkskörper beschädigt',
        270: 'Verstoß gegen Sprengstoffverordnung',
        271: 'Beschädigter Kesselwagen',
        272: 'Gewässerverschmutzung durch Öl',
        273: 'Gewässerverschmutzung durch Öl',
        274: 'Bewusstlose Person',
        275: 'Absicherung Rockkonzert',
        276: 'Schwertransport',
        277: 'Person im Aufzug',
        278: 'LKW in Supermarkt',
        279: 'LKW in Supermarkt',
        280: 'Baum auf Oberleitung',
        281: 'Stromschlag',
        282: 'Geplatzte Wasserleitung',
        283: 'Bürobrand (Groß)',
        284: 'Ostereier-Dieb',
        285: 'Pinsel aus Werkstatt entwendet',
        286: 'Eingestürzter Hasenbau',
        287: 'Angefahrener Osterhase',
        288: 'Brennendes Osternest',
        289: 'Schokoladenspur auf Strasse',
        290: 'Eierkocherbrand',
        291: 'Hasentreffen in Ostereistedt',
        292: 'Tankbetrug',
        293: 'Bluthochdruck',
        294: 'Fußball Bundesliga-Risikospiel',
        295: 'Tankstellenüberfall',
        296: 'Gasunfall in Werkstatt',
        297: 'Arbeitsunfall im Garten',
        298: 'Hilflose Person auf Wasser',
        299: 'Strohballen qualmen in Scheune',
        300: 'Abgestürzter Kletterer',
        301: 'Tiere auf der Fahrbahn',
        302: 'Brennendes Kleinflugzeug',
        303: 'Carportbrand',
        304: 'Angemeldete Demonstration - Gefahrenpotential',
        305: 'Fußball Bundesliga-Risikospiel',
        306: 'Absicherung Rockkonzert - Gefahrenpotential',
        307: 'Spontaner Aufstand',
        308: 'Brennender Müllwagen',
        309: 'Tauchunfall',
        310: 'Tauchunfall',
        311: 'Mitarbeiter unter PKW eingeklemmt',
        312: 'Verunglückter Fallschirmspringer',
        313: 'Verunglückter Fallschirmspringer',
        314: 'Verunglückter Fallschirmspringer',
        315: 'Chemieunfall an Schule',
        316: 'Unbekannte Substanz',
        317: 'Person in Baumaschine eingeklemmt',
        318: 'Ausgelöster Heimrauchmelder',
        319: 'Person in Baugrube',
        320: 'Großfeuer im Krankenhaus',
        321: 'Saunabrand',
        322: 'Geplante Autobahnsperrung',
        323: 'Dehnfugenbrand',
        324: 'Brand in Baumarkt',
        325: 'Absicherung Castor-Transport',
        326: 'Handverletzung durch Feuerwerkskörper',
        327: 'Tiefgaragenbrand',
        328: 'Rauch in Kabine',
        329: 'Rauch in Kabine',
        330: 'Überhitzte Bremsen',
        331: 'Flugzeugzusammenstoß am Boden',
        332: 'Flugzeugbrand',
        333: 'Flugzeugbrand',
        334: 'Brennendes Kleinflugzeug',
        335: 'Brennendes Kleinflugzeug',
        336: 'Absicherung Betankung',
        337: 'Brennender PKW',
        338: 'Motorrad-Brand',
        339: 'Herzinfarkt',
        340: 'akuter Asthma-Anfall',
        341: 'Krampfanfall',
        342: 'Triebwerksbrand',
        343: 'Triebwerksbrand',
        344: 'Mehrere brennende Fahrzeuge',
        345: 'Höhenrettung am Fahrgeschäft',
        346: 'Gebäudesprengung',
        347: 'Helikopter in Baum',
        348: 'Explosion in Biogasanlage',
        349: 'Brandgeruch',
        350: 'Flughafenbrand',
        351: 'Brand in Terminal',
        352: 'Brand in Mehrfamilienhaus',
        353: 'Großkontrolle Betäubungsmittel',
        354: 'Grillunfall',
        355: 'Waffenentzug',
        356: 'Häusliche Gewalt - eskaliert',
        357: 'Bank: Stiller Alarm',
        358: 'Banküberfall',
        359: 'Geplante Razzia - verdächtiger Flüchtig',
        360: 'Brennender Blumenstrauß',
        361: 'Brennender Blumenstrauß',
        362: 'Brennender Blumenstrauß',
        363: 'Brennender Blumenstrauß',
        364: 'Brennender Blumenstrauß',
        365: 'Brennender Blumenstrauß',
        366: 'Vollstreckung Haftbefehl',
        367: 'Vollstreckung Haftbefehl - eskaliert',
        368: 'Brennende Kirche',
        369: 'Austritt Kohlenmonoxid',
        370: 'Geisterfahrer',
        371: 'Fußball aufpumpen',
        372: 'Mannschaftsbus in Halteverbot abgestellt',
        373: 'Behandlung nach Schwalbe',
        374: 'Prellung nach Lattenpraller',
        375: 'Tor gefallen',
        376: 'Pokal geklaut',
        377: 'Überzuckerung',
        378: 'Observation',
        379: 'PKW im Gleisbett',
        380: 'PKW im Gleisbett',
        381: 'PKW im Gleisbett',
        382: 'PKW im Gleisbett',
        383: 'Kind in PKW eingeschlossen',
        384: 'Brennende Ballenpresse',
        385: 'Unfall beim Umpumpen von Flüssigkeiten',
        386: 'Ammoniak austritt',
        387: 'Brennende Pipeline-Isolierung',
        388: 'Feuer in Verwaltungsgebäude',
        389: 'Brand in Chemiepark - Produktion',
        390: 'Sicherheitslandung',
        391: 'Vergiftung',
        392: 'Person durch Hubmaschine eingeklemmt',
        393: 'Einsturzgefährdeter Balkon',
        394: 'LKW auf Stauende',
        395: 'Maschinenbrand in Produktionshalle',
        396: 'Maschinenbrand in Produktionshalle',
        397: 'Schnittwunde',
        398: 'Brennende Absauganlage',
        399: 'Brand in Kabelkanal',
        400: 'Brand in Lackiererei',
        401: 'Umgestürzter Gabelstapler',
        402: 'Brennender PKW',
        403: 'Mülleimerbrand',
        404: 'Mülleimerbrand',
        405: 'Brennender LKW',
        406: 'Brennender LKW',
        407: 'Brennende Filteranlage',
        408: 'Rauchentwicklung an Förderband',
        409: 'Brennender LKW',
        410: 'Mülleimerbrand',
        411: 'Heißluftballon in Hochspannungsmast',
        412: 'Verpuffung',
        413: 'Verpuffung',
        414: 'Verpuffung',
        415: 'Jäger verletzt Passant durch Schuss',
        416: 'Jäger stürzt von Hochsitz',
        417: 'Jäger durch Wildtier verletzt',
        418: 'Absicherung Pannen-LKW',
        419: 'Austritt Flüssiggas',
        420: 'Schlechter Allgemeinzustand',
        421: 'PKW in Bushaltestelle',
        422: 'Sachbeschädigung an PKW',
        423: 'Brand in Klassenraum',
        424: 'Großbrand Müllverbrennungsanlage',
        425: 'Verstauchter Knöchel',
        426: 'Gebrochenes Bein',
        427: 'Gebrochener Arm',
        428: 'Schneelast auf Dach',
        429: 'Staubexplosion',
        430: 'Ammoniak Austritt in Eishalle'
      }
    };
    I18n.translations.en.lssm.missionKeywordDefaults = {
      name: 'Mission Keywords',
      settingsName: 'Mission Keywords - Settings',
      domain: 'missionchief.com',
      fw: 'FIRE',
      thl: 'TECH',
      abc: 'CBRN',
      rd: 'MED',
      ktp: 'MEDT',
      pol: 'POL',
      thw: 'TECH',
      bp: 'POL',
      bma: 'FAS',
      bmaLong: 'Fire Alarm System',
      show: 'Show/Hide',
      keywords: {
        0: 'Bin fire',
        1: 'Container fire',
        2: 'Burning car',
        3: 'Burning motorbike',
        4: 'Burning grass',
        5: 'Room fire',
        6: 'Garden shed fire',
        7: 'Burning leaves',
        8: 'Bulk trash fire',
        9: 'Bale of straw fire',
        10: 'Tractor fire',
        11: 'Burning callbox',
        12: 'Tree on the road',
        13: 'Burning truck',
        14: 'Little field fire',
        15: 'Little wildfire',
        16: 'Caravan fire',
        17: 'Mailbox on fire',
        18: 'Brush pile',
        19: 'Burning trailer',
        20: 'Basement fire',
        21: 'Chimney fire',
        22: 'Roof fire',
        23: 'Grease Fire',
        24: 'Burning bus shelter',
        25: 'Road accident',
        26: 'Garage fire',
        27: 'Gas Leak',
        28: 'Fireplace fire',
        29: 'Harvester fire',
        30: 'Wastebin fire',
        31: 'Wastebin fire',
        32: 'Wastebin fire',
        33: 'Wastebin fire',
        34: 'Alcoholic intoxication',
        35: 'Nosebleed',
        36: 'Chest Pains',
        37: 'Acute asthma',
        38: 'Seizure',
        39: 'Fever',
        40: 'Fallen person',
        41: 'Major fire',
        42: 'Manhole Fire',
        43: 'Diabetic problems',
        44: 'Burning machine',
        45: 'Burning locomotive',
        46: 'Gas station fire',
        47: 'Dangerous goods truck accident',
        48: 'Shoplifting',
        49: 'Shoplifting',
        50: 'Parked car accident',
        51: 'Parked car accident',
        52: 'Metal burglary',
        53: 'Pickpocketing',
        54: 'Fare dodger',
        55: 'Fare dodger',
        56: 'Fare dodger',
        57: 'Fare dodger',
        58: 'Parked car accident',
        59: 'Brawl',
        60: 'Rioter',
        61: 'Unannounced demonstration',
        62: 'Pile-up',
        63: 'Burning bogle',
        64: 'Burning pumpkin field',
        65: 'Pumpkin soup overcooked',
        66: 'Witch in tree',
        67: 'Zombie bite',
        68: 'Erupted Monster',
        69: 'Pumpkin stolen',
        70: 'Frankenstein sighted',
        71: 'candy theft',
        72: 'Person check',
        73: 'Obstruction of traffic',
        74: 'Theft of property from vehicles',
        75: 'Tree on bikeway',
        76: 'Burning substation',
        77: 'Burning substation',
        78: 'Person under tree',
        79: 'Theft at christmas market',
        80: 'Burning christmas market stall',
        81: 'Fire at christmas market',
        82: 'Traffic accident - ice',
        83: 'Burning christmas tree',
        84: 'Burning advent wreath',
        85: 'Brawl at christmas market',
        86: 'MVA Rollover',
        87: 'Industrial Fire',
        88: 'Partial Building Collapse',
        89: 'Trench Rescue',
        90: 'Officer Down',
        91: 'Concert',
        92: 'Soccer Game',
        93: 'Baseball Game',
        94: 'Prisoner Escape',
        95: 'Fleeing Suspect',
        96: 'Missing Person',
        97: 'Warrant Standby',
        98: 'Unknown Tanker Spill',
        99: 'Commercial Fire',
        100: 'Animal Attack',
        101: 'Unknown Tanker Spill',
        102: 'High Rise Fire',
        103: 'Domestic Dispute',
        104: 'Hostage Taken',
        105: 'Active Shooter',
        106: 'High-Risk Warrant',
        107: 'Drug Warrant',
        108: 'Anaphylaxis',
        109: 'Noise Complaint',
        110: 'Residential Fire',
        111: 'Stabbing',
        112: 'Bomb Explosion',
        113: 'Smoke in Cabin',
        114: 'Smoke in Cabin',
        115: 'Braking Overheat',
        116: 'Braking Overheat',
        117: 'Engine Fire',
        118: 'Engine Fire',
        119: 'Food Poisoning',
        120: 'Large Aircraft Crash',
        121: 'Aircraft Hijack',
        122: 'Carbon Monoxide Alarm',
        123: 'Bank Robbery',
        124: 'Shooting',
        125: 'Vehicle Accident - Entrapment',
        126: 'Overdose',
        127: 'Fire in an Office Building',
        128: 'Aggressive Passenger',
        129: 'Aggressive Passenger',
        130: 'Powerline Down',
        131: 'Parole Violation',
        132: 'Allergic Reaction',
        133: 'Stolen Credit Card',
        134: 'Search of a vehicle',
        135: 'Small Violent Protest',
        136: 'Medium Violent Protest',
        137: 'Drug Deal',
        138: 'Smoke Investigation',
        139: 'Drug Lab Fire',
        140: 'Gas Station Robbery',
        141: 'Elevator Rescue',
        142: 'Warehouse Fire',
        143: 'Assassination Threat',
        144: 'Truck in House Wall',
        145: 'Burning Garbage Truck',
        146: 'Child Birth',
        147: 'Keys Locked in Vehicle',
        148: 'Stuck Climber',
        149: 'Smoke Detector Check',
        150: 'Freight Train Derailment',
        151: 'Freight Train Derailment',
        152: 'Freight Train Derailment',
        153: 'Barn Fire',
        154: 'Chlorine leak',
        155: 'Fire in Hospital',
        156: 'Turbulence Injury',
        157: 'Turbulence Injury',
        158: 'Accident Involving a Bus',
        159: 'Serious Accident Involving a Bus',
        160: 'Lost Child',
        161: 'DUI Checkpoint',
        162: 'Light Aircraft Crash (Airfield)',
        163: 'Light Aircraft Crash',
        164: 'Cable theft',
        165: 'Drowning',
        166: 'Drowning',
        167: 'Car in river',
        168: 'Car in lake',
        169: 'Small flooding',
        170: 'Medium flooding',
        171: 'Large flooding',
        172: 'Giant flooding',
        173: 'Light aircraft crash in water',
        174: 'Light aircraft crash in water',
        175: 'Bridge Collapse',
        176: 'Stroke',
        177: 'Unconscious Person',
        178: 'Hemorrhage',
        179: 'Burst water main',
        180: 'Shots fired at Officer',
        181: 'School fire',
        182: 'Cafeteria fire',
        183: 'Fire in fast food restaurant',
        184: 'Container Ship Fire',
        185: 'Dock Crane fire',
        186: 'Recycling Centre fire',
        187: 'Kidnaping',
        188: 'Cruise ship sinking',
        189: 'Sinking boat',
        190: 'Sinking boat',
        191: 'Sinking boat',
        192: 'Traffic accident with train',
        193: 'Animal Rescue',
        194: 'Large MVA in tunnel',
        195: 'Single vehicle fire in tunnel',
        196: 'Kitchen Fire',
        197: 'Small boat fire',
        198: 'Small boat fire',
        199: 'Small boat fire',
        200: 'Person with a weapon',
        201: 'VIP appearance',
        202: 'Large Field Fire',
        203: 'Natural gas odor',
        204: 'Ammonia Leak (Gas Alarm System)',
        205: 'Multiple vehicle fire in tunnel',
        206: 'Transformer fire',
        207: 'Caller Hangup',
        208: 'Power Plant fire',
        209: 'Factory Fire minor',
        210: 'Factory Fire major',
        211: 'Multiple vehicles on fire',
        212: 'Fire on farm medium',
        213: 'Fire on farm large',
        214: 'Scrapyard fire',
        215: 'Animal rescue from drain',
        216: 'Home Invasion',
        217: 'Museum Fire',
        218: 'Cardiac Arrest',
        219: 'Respiratory Arrest',
        220: 'Difficulty Breathing',
        221: 'Difficulty Breathing',
        222: 'Difficulty Breathing',
        223: 'Back Pain',
        224: 'Vehicle Pursuit',
        225: 'Landing Gear failure',
        226: 'Landing Gear failure',
        227: 'Airport Terminal Collapse (Small)',
        228: 'Airport Terminal Collapse (Large)',
        229: 'Airport Terminal Collapse (Major)',
        230: 'Hazardous materials truck fire in tunnel',
        231: 'Hazardous materials truck fire',
        232: 'Full Building Collapse'
      }
    };
    I18n.translations.nl.lssm.missionKeywordDefaults = {
      name: 'Steekwoorden bij meldingen',
      settingsName: 'Steekwoorden bij meldingen - Instellingen',
      domain: 'meldkamerspel.com',
      fw: 'BRAND',
      thl: 'HV',
      abc: 'OGS',
      rd: 'A 1',
      ktp: 'B 1',
      pol: 'P 1',
      thw: 'HV',
      bp: 'POL',
      bma: 'OMS',
      bmaLong: 'OMS',
      show: 'Verberg/toon',
      keywords: {
        0: 'Brandende afvalbak',
        1: 'Brandende container',
        2: 'Brandende personenauto',
        3: 'Brandende motorfiets',
        4: 'Brandend gras',
        5: 'Brand in woonkamer',
        6: 'Brand in tuinhuis',
        7: 'Brandende boom',
        8: 'Brandend afval',
        9: 'Brandend hooi',
        10: 'Brandende traktor',
        11: 'Brandende bromfiets',
        12: 'Boom op de weg',
        13: 'Brandende vrachtwagen',
        14: 'Heidebrand',
        15: 'Bosbrand',
        16: 'Brand in woonwagen',
        17: 'Brandende dixi',
        18: 'Brandende struik',
        19: 'Brandende aanhangwagen',
        20: 'Brand in kelder',
        21: 'Schoorsteenbrand',
        22: 'Brandend dak',
        23: 'Brand in cafetaria',
        24: 'Brandend bushokje',
        25: 'Verkeersongeval met beknelling',
        26: 'Brand in supermarkt',
        27: 'Persoon aangereden',
        28: 'Brand in landbouwschuur',
        29: 'Machine brand',
        30: 'Lekkende dieseltank',
        31: 'Oliespoor',
        32: 'Schoorsteenbrand (woning met rietenkap)',
        33: 'Brandende landbouwmachine',
        34: 'Brand in supermarkt',
        35: 'Brand in ziekenhuis',
        36: 'Brandende goederenwagon',
        37: 'Brandende afvalbak',
        38: 'Brandende afvalbak',
        39: 'Brandende afvalbak',
        40: 'Brandende afvalbak',
        41: 'Brand in kantoorpand',
        42: 'Brand in tankstation',
        43: 'Kettingbotsing',
        44: 'Liftopsluiting',
        45: 'Overdosis alcohol',
        46: 'Bloedneus',
        47: 'Pijn op de borst',
        48: 'Astma aanval',
        49: 'Beroerte',
        50: 'Koortsstuip',
        51: 'Gevallen persoon',
        52: 'Brand in garagebedrijf',
        53: 'Brand in sporthal',
        54: 'Brand in sporthal',
        55: 'Brand in sporthal',
        56: 'Brand in sporthal',
        57: 'Kat in boom',
        58: 'Buitenbrand',
        59: 'Brand in opslagloods',
        60: 'Brand in slaapkamer',
        61: 'Brand in slaapkamer',
        62: 'Brand in keuken',
        63: 'Brand in keuken',
        64: 'Brand in keuken',
        65: 'Takken op de weg',
        66: 'Boom op fietspad',
        67: 'Omgewaaide bouwsteiger',
        68: 'Boom op auto',
        69: 'Persoon bekneld onder boom',
        70: 'Winkeldiefstal',
        71: 'Winkeldiefstal',
        72: 'Winkeldiefstal',
        73: 'Tasjesdief',
        74: 'Huiselijk geweld',
        75: 'Bestuurder onder invloed',
        76: 'Klein vliegtuig neergestort',
        77: 'Klein vliegtuig neergestort',
        78: 'Rookontwikkeling in winkel',
        79: 'Gevallen fietser',
        80: 'Allergische reactie',
        81: 'Verward persoon',
        82: 'Vrachtwagen gekanteld',
        83: 'Val van hoogte (> 5 meter)',
        84: 'Ernstige brandwonden',
        85: 'Aanrijding voetganger (> 30 km/u)',
        86: 'Aanrijding door trein',
        87: 'Beginnende geboorte',
        88: 'Hersenbloeding',
        89: 'Nek- wervelletsel',
        90: 'Ontwrichting',
        91: 'Psychiatrisch beeld',
        92: 'Botbreuk',
        93: 'Gebroken rib',
        94: 'Hoofdletsel',
        95: 'Hyperventilatie',
        96: 'Hittekramp',
        97: 'Hoofdwond',
        98: 'Vreemde lucht',
        99: 'Stankoverlast',
        100: 'Ammoniakalarm in opslagloods',
        101: 'Koolmonoxide vrijgekomen',
        102: 'Lekkende goederenwagon',
        103: 'Schoorsteenbrand',
        104: 'Brandgerucht',
        105: 'Buitensluiting',
        106: 'Schaap in sloot',
        107: 'Persoon bekneld in machine',
        108: 'Ongeval met trein en personenauto',
        109: 'Ongeval met trein en persoon',
        110: 'Brand in vakantiewoning',
        111: 'Brand in vakantiewoning',
        112: 'Overval winkel',
        113: 'Overval winkel',
        114: 'Brandend dak',
        115: 'Brandend dak',
        116: 'Voetbalwedstrijd',
        117: 'Voetbalwedstrijd (risicowedstrijd)',
        118: 'Hardloopevenement',
        119: 'Begeleiding orkest',
        120: 'Begeleiding wielrenners',
        121: 'Test brandalarm school',
        122: 'Overval winkel',
        123: 'Overval winkel',
        124: 'Achtervolging personenauto',
        125: 'Vermist persoon',
        126: 'Brand in landbouwschuur',
        127: 'Brand in landbouwschuur',
        128: 'Heidebrand',
        129: 'Heidebrand',
        130: 'Brand in cafetaria',
        131: 'Brand in cafetaria',
        132: 'Brandende bus',
        133: 'Brandende bestelwagen',
        134: 'Brandende haag',
        135: 'Brandende papiercontainer',
        136: 'Brandende caravan',
        137: 'Besteld vervoer',
        138: 'Brand in meterkast',
        139: 'Natuurbrand',
        140: 'Natuurbrand',
        141: 'Natuurbrand',
        142: 'Natuurbrand',
        143: 'Natuurbrand',
        144: 'Natuurbrand',
        145: 'Natuurbrand',
        146: 'Brandende vogelverschrikker',
        147: 'Brandend pompoenveld',
        148: 'Overkookte pompoensoep',
        149: 'Heks vast in boom',
        150: 'Monster uitgebroken',
        151: 'Gestolen pompoenen',
        152: 'Frankenstein gespot',
        153: 'Snoep diefstal',
        154: 'Horrorclown gespot',
        155: 'Gaslekkage',
        156: 'Gaslekkage',
        157: 'Brand in ziekenhuis',
        158: 'Brand in ziekenhuis',
        159: 'Brand in sporthal',
        160: 'Brandende cadeautjes',
        161: 'Sinterklaas van dak gegleden',
        162: 'Pepernoot op hoofd',
        163: 'Piet bestolen',
        164: 'Kind geschrokken',
        165: 'Piet klem in schoorsteen',
        166: 'Demonstratie zwarte piet',
        167: 'Schoenen dief',
        168: 'Verstikking in pepernoot',
        169: 'Brandende kerstboom',
        170: 'Brandende kerstboom',
        171: 'Verkeersongeval door gladheid',
        172: 'Gevallen kerstman',
        173: 'Ruzie op de kerstmarkt',
        174: 'Diefstal op de kerstmarkt',
        175: 'Brandende kerstmarktkraam',
        176: 'Gevallen schaatser',
        177: 'Gevallen persoon door gladheid',
        178: 'Donkere dagen offensief',
        179: 'Snijwond door gebroken kerstbal',
        180: 'Bergen object uit water voor politie',
        181: 'Verkeersongeval met beknelling',
        182: 'Personenauto in sloot',
        183: 'Paard in sloot',
        184: 'Eend verstrikt in visdraad',
        185: 'Verlaten kinderfiets langs waterkant',
        186: 'Parkeergarage onder water',
        187: 'Kelder onder water',
        188: 'Gevaarlijk hangende tak',
        189: 'Boom op dak',
        190: 'Straat onder water',
        191: 'Losgewaaide dakbedekking',
        192: 'Parkeerterrein onder water',
        193: 'Koe in sloot',
        194: 'Koe in gierput',
        195: 'Lekkende woonboot',
        196: 'Brand in woonwagen',
        197: 'Brandende vrachtwagen',
        198: 'Brand in woonkamer',
        199: 'Inbraak in woning',
        200: 'Drugslab aangetroffen',
        201: 'Vechtpartij in café',
        202: 'Steekincident',
        203: 'Verkeersongeval met gevaarlijke stoffen',
        204: 'Verkeersongeval met gevaarlijke stoffen',
        205: 'Persoon te water',
        206: 'Persoon te water',
        207: 'Personenauto te water',
        208: 'Personenauto te water',
        209: 'Aanvaring met vrachtschip en motorboot',
        210: 'Aanvaring met vrachtschip en motorboot',
        211: 'Aanvaring met vrachtschip en motorboot',
        212: 'Omgeslagen zeilboot',
        213: 'Omgeslagen zeilboot',
        214: 'Bosbrand',
        215: 'Bosbrand',
        216: 'Bosbrand',
        217: 'Plofkraak',
        218: 'Plofkraak',
        219: 'Open dag (klein)',
        220: 'Open dag (groot)',
        221: 'Inval in woning',
        222: 'Inbraak in woning',
        223: 'Brand in kelder',
        224: 'Brand in kelder',
        225: 'Benauwdheid',
        226: 'Val van trap',
        227: 'Assistentie treinconducteur',
        228: 'Assistentie treinconducteur',
        229: 'Brand in tankstation',
        230: 'Onwelwording',
        231: 'Vernieling bushokje',
        232: 'Buspassagier weigert te betalen',
        233: 'Brand in tuinhuis',
        234: 'Vliegtuig neergestort',
        235: 'Overdosis drugs',
        236: 'Schietincident',
        237: 'Brand in werkplaats',
        238: 'Brand in werkplaats',
        239: 'Verstikking',
        240: 'Vergiftiging',
        241: 'Zwemmer vermist',
        242: 'Verlaten kleding langs waterkant',
        243: 'Verdachte situatie',
        244: 'Persoon van podium gevallen',
        245: 'Ontruimen kraakpand',
        246: 'Persoon vermist',
        247: 'Persoon vermist',
        248: 'Persoon vermist',
        249: 'Straatroof',
        250: 'Opnemen aangifte inbraak',
        251: 'Vrachtwagen te water',
        252: 'Vrachtwagen te water',
        253: 'Grote boek van Sinterklaas aangespoeld',
        254: 'Brandende goederenwagon',
        255: 'Brandende goederenwagon',
        256: 'Geluidsoverlast',
        257: 'Auto-inbraak',
        258: 'Brand in flatwoning',
        259: 'Brand in flatwoning',
        260: 'Brandend speeltoestel',
        261: 'Persoon door glas gevallen',
        262: 'Burenruzie',
        263: 'Brandende personenauto in parkeergarage',
        264: 'Brandende personenauto in parkeergarage',
        265: 'Vliegtuig met hydraulisch probleem',
        266: 'Vliegtuig met rook in cabine',
        267: 'Vliegtuig met brandgeur in cabine',
        268: 'Vliegtuig met probleem met landingsgestel',
        269: 'Vliegtuig met brandmelding in vrachtruim',
        270: 'Vliegtuig buiten start-/landingsbaan beland',
        271: 'Rookontwikkeling in vrachtruim vliegtuig',
        272: 'Klein vliegtuig met motorisch probleem',
        273: 'Klein vliegtuig neergestort',
        274: 'Klein vliegtuig neergestort',
        275: 'Brandend klein vliegtuig',
        276: 'Brandend klein vliegtuig',
        277: 'Pijn op de borst',
        278: 'Beroerte',
        279: 'Bedreiging',
        280: 'Brand in garagebedrijf',
        281: 'Brand in garagebedrijf',
        282: 'Brand in garagebedrijf',
        283: 'Val van paard',
        284: 'Gevaarlijk rijgedrag',
        285: 'Brand in supermarkt',
        286: 'Kind vast in boom',
        287: 'Brand in magazijn',
        288: 'Brand in magazijn',
        289: 'Brand in magazijn',
        290: 'Brand in magazijn',
        291: 'Brand in magazijn',
        292: 'Ongeval met trein en vrachtwagen',
        293: 'Ongeval met trein en vrachtwagen',
        294: 'Overlast jeugd',
        295: 'Overlast zwervers',
        296: 'Brand in museum',
        297: 'Brand in museum',
        298: 'Brand in museum',
        299: 'Brandend plezierjacht',
        300: 'Brandend plezierjacht',
        301: 'Inbraakalarm',
        302: 'Brand in kantoorgebouw',
        303: 'Brand in kantoorgebouw',
        304: 'Brand in kantoorgebouw',
        305: 'Verkeersongeval met touringcar',
        306: 'Verkeersongeval met touringcar',
        307: 'Verkeersongeval met touringcar',
        308: 'Natuurbrand',
        309: 'Natuurbrand',
        310: 'Verkeersongeval met scooter en fietser',
        311: 'Verkeersongeval met fietser en fietser',
        312: 'Lekkende goederenwagon',
        313: 'Brand in passagierstrein',
        314: 'Brand in passagierstrein',
        315: 'Brand in passagierstrein',
        316: 'Bedreiging met vuurwapen',
        317: 'Bedreiging met vuurwapen',
        318: 'Brand op binnenvaartschip',
        319: 'Brand op binnenvaartschip',
        320: 'Brand op binnenvaartschip',
        321: 'Brandende wegberm',
        322: 'Brandende wegberm',
        323: 'Verkeersongeval met motorfiets',
        324: 'Verkeersongeval met personenauto en motorfiets',
        325: 'Verkeersongeval met fietser en motorfiets',
        326: 'Brand in landbouwschuur',
        327: 'Brand in landbouwschuur',
        328: 'Persoon onwel na mixen mest',
        329: 'Verwaarloosde hond in woning',
        330: 'Vechtpartij in café',
        331: 'Inbraak in bedrijfspand',
        332: 'Inbraak in bedrijfspand',
        333: 'Inbraak in bedrijfspand',
        334: 'Brand in schoolgebouw',
        335: 'Brand in schoolgebouw',
        336: 'Brand in schoolgebouw',
        337: 'Huiselijk geweld',
        338: 'Huiselijk geweld',
        339: 'Lekkende LPG installatie',
        340: 'Lekkende LPG installatie',
        341: 'Nacontrole brand',
        342: 'Nacontrole brand',
        343: 'Nacontrole brand',
        344: 'Vreemde lucht in kantoorgebouw',
        345: 'Vreemde lucht in kantoorgebouw',
        346: 'Brand in opslagloods met gevaarlijke stoffen',
        347: 'Brand bij afvalverwerker',
        348: 'Zwemmer vermist',
        349: 'Zwemmer vermist',
        350: 'Insluiping in woning',
        351: 'Inbraakalarm woning',
        352: 'Brand in terminal',
        353: 'Brand in terminal',
        354: 'Brand in terminal',
        355: 'Heidebrand',
        356: 'Heidebrand',
        357: 'Natuurbrand',
        358: 'Hoge bloeddruk',
        359: 'Lage bloeddruk',
        360: 'Brand in bovenwoning',
        361: 'Brand in bovenwoning',
        362: 'Brand in flatwoning',
        363: 'Brand op passagiersschip',
        364: 'Brand op passagiersschip',
        365: 'Brand op passagiersschip',
        366: 'Personen op dak school',
        367: 'Gestolen scooter gevonden',
        368: 'Verkeersongeval met vrachtwagen en fietser',
        369: 'Verkeersongeval met vrachtwagen en fietser',
        370: 'Verkeersongeval met vrachtwagen en fietser',
        371: 'Verlaten slee langs waterkant',
        372: 'Brandende kerststal',
        373: 'Brandwonden door gourmetstel',
        374: 'Geluidsoverlast door kerstmuziek',
        375: 'Persoon bekneld onder kerstpakketten',
        376: 'Persoon te water',
        377: 'Persoon te water',
        378: 'Vreemde lucht in winkelcentrum',
        379: 'Vreemde lucht in winkelcentrum',
        380: 'Epileptische aanval',
        381: 'Hevige bloeding',
        382: 'Suikertekort',
        383: 'Brand in parkeergarage',
        384: 'Brand in parkeergarage',
        385: 'Brand in parkeergarage',
        386: 'Brand in parkeergarage',
        387: 'Bouwvakker van hoogte gevallen',
        388: 'Bouwvakker van hoogte gevallen',
        389: 'Bouwvakker bekneld onder bouwmateriaal'
      }
    };

    var managedSettings = {
      "id": LSS_MISSIONKEYWORD_STORAGE,
      "title": I18n.t('lssm.missionKeywordDefaults.name'),
      "settings": {
        "missionKeywordShowHideButton": {
          "default": "",
          "ui": {
            "label": I18n.t('lssm.missionKeywordDefaults.show'),
            "type": "button",
            "custom_function_event": "click",
            "custom_function": function() {
              $('[id^=' + LSS_MISSIONKEYWORD_STORAGE + '_missionKeyword-]').toggle();
            }
          }
        }
      }
    };

    // Einsatz-ID zu Stichwort
    var DEFAULT_AAO_DE = {
      0: 'B 1',
      1: 'B 2',
      2: 'B 2',
      3: 'B 1',
      4: 'B 1',
      5: 'B 3',
      6: 'B 2',
      7: 'B 1',
      8: 'B 1',
      9: 'B 2',
      10: 'B 2',
      11: 'B 1',
      12: 'THL 1',
      13: 'B 3',
      14: 'B 2',
      15: 'B WALD',
      16: 'B 2',
      17: 'B 1',
      18: 'B 1',
      19: 'B 2',
      20: 'B 3',
      21: 'B 2',
      22: 'B 3',
      23: 'B 3',
      24: 'B 1',
      25: 'THL 1',
      26: 'B 3',
      27: 'THL 1',
      28: 'B 3',
      29: 'B 3',
      30: 'THL 1',
      31: 'THL 1',
      32: 'B 2',
      33: 'B 3',
      34: 'B 3',
      35: 'B 4',
      36: 'B 4',
      37: 'B 1',
      38: 'B 1',
      39: 'B 1',
      40: 'B 1',
      41: 'ABC B',
      42: 'ABC B 4',
      43: 'THL 5',
      44: 'RD 1',
      45: 'RD 1',
      46: 'RD 2',
      47: 'RD 2',
      48: 'RD 2',
      49: 'RD 1',
      50: 'RD 1',
      51: 'B 4',
      52: 'B 1',
      53: 'THL 1',
      54: 'RD 1',
      55: 'B 1',
      56: 'RD 1',
      57: 'RD 1',
      58: 'RD 1',
      59: 'ABC 3',
      60: 'POL 1',
      61: 'POL 1',
      62: 'POL 1',
      63: 'POL 1',
      64: 'POL 1',
      65: 'POL 1',
      66: 'POL 1',
      67: 'POL 1',
      68: 'POL 1',
      69: 'POL 1',
      70: 'POL 1',
      71: 'POL 1',
      72: 'THL P HÖHENRETTUNG',
      73: 'POL 3',
      74: 'POL 1',
      75: 'POL 7',
      76: 'B 3',
      77: 'THL P WOHNUNG',
      78: 'THL 1',
      79: 'THL P HÖHENRETTUNG',
      80: 'B 3',
      81: 'POL 1',
      82: 'POL 1',
      83: 'ABC THL 3',
      84: 'B ZUG',
      85: 'POL 1',
      86: 'B 4',
      87: 'THL VU FLUGZEUG 1',
      88: 'B 1',
      89: 'THL 2',
      90: 'POL 1',
      91: 'THL 1',
      92: 'RD 2',
      93: 'B 3',
      94: 'THL 1',
      95: 'THL 2',
      96: 'B 3',
      97: 'ABC ÖL',
      98: 'POL 1',
      99: 'THL VU FLUGZEUG 2',
      100: 'B 3',
      101: 'B 3',
      102: 'B 3',
      103: 'B 3',
      104: 'B 3',
      105: 'B 3',
      106: 'POL 5',
      107: 'POL 5',
      108: 'RD 2',
      109: 'RD 2',
      110: 'RD 1',
      111: 'B 1',
      112: 'B 1',
      113: 'B 1',
      114: 'THL 1',
      115: 'RD 1',
      116: 'POL 4',
      117: 'POL 1',
      118: 'POL 3',
      119: 'POL 1',
      120: 'THL 2',
      121: 'THL 2',
      122: 'THL 1',
      123: 'THL 1',
      124: 'THL 1',
      125: 'THL 1',
      126: 'THL 1',
      127: 'THL 1',
      128: 'POL 1',
      129: 'B 1',
      130: 'POL 2',
      131: 'B 2',
      132: 'B 2',
      133: 'B 2',
      134: 'B WALD',
      135: 'B WALD',
      136: 'B WALD',
      137: 'B WALD',
      138: 'B 2',
      139: 'B 2',
      140: 'B 2',
      141: 'B 2',
      142: 'B 3',
      143: 'B 1',
      144: 'B 1',
      145: 'POL 1',
      146: 'B 4',
      147: 'RD KTP',
      148: 'POL 1',
      149: 'POL 1',
      150: 'POL 1',
      151: 'POL 1',
      152: 'POL 2',
      153: 'POL 1',
      154: 'RD 1',
      155: 'RD 1',
      156: 'RD 1',
      157: 'RD 2',
      158: 'THL 1',
      159: 'THL 1',
      160: 'THL 1',
      161: 'THL 1',
      162: 'THL 1',
      163: 'THL 1',
      164: 'RD 1',
      165: 'RD 1',
      166: 'THL 1',
      167: 'THL 1',
      168: 'THL 1',
      169: 'THL 1',
      170: 'THL 1',
      171: 'THL 1',
      172: 'THL 1',
      173: 'THL 1',
      174: 'THW 1',
      175: 'THW 1',
      176: 'THW 1',
      177: 'THL EINSTURZ',
      178: 'ABC THL 3',
      179: 'RD 2',
      180: 'RD 2',
      181: 'RD 2',
      182: 'RD 1',
      183: 'RD 1',
      184: 'RD 1',
      185: 'RD 1',
      186: 'B 4',
      187: 'B 3',
      188: 'POL 1',
      189: 'POL 1',
      190: 'POL 1',
      191: 'THL 1',
      192: 'B ELEKTRO',
      193: 'B ELEKTRO',
      194: 'THL 1',
      195: 'BP 1',
      196: 'BP 1',
      197: 'BP 1',
      198: 'BP 1',
      199: 'BP 1',
      200: 'BP 2',
      201: 'BP 3',
      202: 'POL 1',
      203: 'B 2',
      204: 'B 4',
      205: 'B 4',
      206: 'B 5',
      207: 'ABC 3',
      208: 'ABC 2',
      209: 'POL 1',
      210: 'RD 2',
      211: 'RD 1',
      212: 'RD 1',
      213: 'B EXPLOSION',
      214: 'B 4',
      215: 'ABC 3',
      216: 'B 1',
      217: 'B 1',
      218: 'B 1',
      219: 'B 1',
      220: 'B 1',
      221: 'THL VU ZUG',
      222: 'THL VU ZUG',
      223: 'SICHERHEITSWACHE',
      224: 'SICHERHEITSWACHE',
      225: 'SICHERHEITSWACHE',
      226: 'VERKEHRSSICHERUNG',
      227: 'ABSICHERUNG',
      228: 'VERKEHRSSICHERUNG',
      229: 'VERKEHRSSICHERUNG',
      230: 'B 1',
      231: 'POL 10',
      232: 'POL 3',
      233: 'POL 2',
      234: 'THL BOMBENFUND',
      235: 'THL P HÖHENRETTUNG',
      236: 'THL P HÖHENRETTUNG',
      237: 'THL ZUG',
      238: 'THL 2',
      239: 'THL 2',
      240: 'ABC 1',
      241: 'POL 1',
      242: 'POL 3',
      243: 'THL 1',
      244: 'THL WASSER',
      245: 'THL WASSER',
      246: 'THL WASSER',
      247: 'THL WASSER',
      248: 'THL WASSER',
      249: 'THL WASSER',
      250: 'THL WASSER',
      251: 'THL WASSER',
      252: 'THL WASSER',
      253: 'THL WASSER',
      254: 'THL WASSER',
      255: 'THL WASSER',
      256: 'THL VU SCHIFF',
      257: 'POL 2',
      258: 'THL 3',
      259: 'B 1',
      260: 'B 1',
      261: 'B 1',
      262: 'B 3',
      263: 'B 1',
      264: 'B 3',
      265: 'B 1',
      266: 'B 1',
      267: 'POL 1',
      268: 'B 4',
      269: 'POL 1',
      270: 'POL 1',
      271: 'THL ZUG',
      272: 'ABC WASSER',
      273: 'ABC WASSER',
      274: 'RD 2',
      275: 'ABSICHERUNG',
      276: 'POL 4',
      277: 'THL 1',
      278: 'THL 2',
      279: 'THL 2',
      280: 'THL 3',
      281: 'RD 2',
      282: 'THL 1',
      283: 'B 5',
      284: 'POL 1',
      285: 'POL 1',
      286: 'THL EINSTURZ',
      287: 'POL 1',
      288: 'B 1',
      289: 'THL 1',
      290: 'B 2',
      291: 'BP 3',
      292: 'POL 1',
      293: 'RD 1',
      294: 'BP 9',
      295: 'POL 6',
      296: 'THL 2',
      297: 'RD 1',
      298: 'THL WASSER',
      299: 'B 3',
      300: 'THL P HÖHENRETTUNG',
      301: 'POL 2',
      302: 'B 3',
      303: 'B 2',
      304: 'BP 3',
      305: 'BP 10',
      306: 'BP 4',
      307: 'BP 4',
      308: 'B 2',
      309: 'RD 2',
      310: 'RD 2',
      311: 'THL 1',
      312: 'RD 2',
      313: 'RD 2',
      314: 'RD 2',
      315: 'ABC 2',
      316: 'ABC 2',
      317: 'THL 1',
      318: 'B 3',
      319: 'THL 1',
      320: 'B 5',
      321: 'B 2',
      322: 'POL 2',
      323: 'B 3',
      324: 'B 5',
      325: 'SICHERHEITSWACHE',
      326: 'RD 2',
      327: 'B 4',
      328: 'B 2',
      329: 'B 2',
      330: 'B 1',
      331: 'THL VU FLUGZEUG 2',
      332: 'B 4 FLUGZEUG',
      333: 'B 4 FLUGZEUG',
      334: 'THL VU FLUGZEUG 1',
      335: 'THL VU FLUGZEUG 1',
      336: 'THL 1',
      337: 'B 1',
      338: 'B 1',
      339: 'RD 2',
      340: 'RD 2',
      341: 'RD 2',
      342: 'B 1',
      343: 'B 1',
      344: 'B 2',
      345: 'THL P HÖHENRETTUNG',
      346: 'ABSICHERUNG',
      347: 'THL 3',
      348: 'ABC EXPLOSION B 5',
      349: 'B 1',
      350: 'B 8',
      351: 'B 4',
      352: 'B 4',
      353: 'SICHERHEITSWACHE',
      354: 'RD 2',
      355: 'MEK 1',
      356: 'SEK 1',
      357: 'POL 1',
      358: 'SEK 2',
      359: 'BP 3',
      360: 'B 0.1',
      361: 'B 0.1',
      362: 'B 0.1',
      363: 'B 0.1',
      364: 'B 0.1',
      365: 'B 0.1',
      366: 'POL 1',
      367: 'SEK 1',
      368: 'B 4',
      369: 'B 1',
      370: 'POL 2',
      371: 'THL 0.5',
      372: 'POL 0.5',
      373: 'RD 0.5',
      374: 'RD 0.5',
      375: 'THL 0.5',
      376: 'POL 0.75',
      377: 'RD 1',
      378: 'MEK 1',
      379: 'THL 2',
      380: 'THL 2',
      381: 'THL 2',
      382: 'THL 2',
      383: 'POL 1',
      384: 'B 1',
      385: 'ABC 1',
      386: 'ABC 1',
      387: 'ABC 2',
      388: 'B 1',
      389: 'ABC 4',
      390: 'B 1',
      391: 'RD 2',
      392: 'THL 1 Person',
      393: 'THL 1',
      394: 'THL 3 LKW',
      395: 'B 4',
      396: 'B 4',
      397: 'RD 1',
      398: 'B 4',
      399: 'B 2',
      400: 'B 5',
      401: 'THL 1',
      402: 'B 2',
      403: 'B 1',
      404: 'B 1',
      405: 'B 3',
      406: 'B 3',
      407: 'B 4',
      408: 'B 1',
      409: 'B 3',
      410: 'B 1',
      411: 'THL 1 BALLON',
      412: 'B 4',
      413: 'B 4',
      414: 'B 4',
      415: 'RD 2',
      416: 'RD 1',
      417: 'RD 1',
      418: 'POL 1',
      419: 'ABC 2',
      420: 'RD 1',
      421: 'THL 1',
      422: 'POL 1',
      423: 'B 3',
      424: 'B 5',
      425: 'RD 1',
      426: 'RD 2',
      427: 'RD 2',
      428: 'THL 2',
      429: 'B 4',
      430: 'ABC 3'
    };
    var DEFAULT_AAO_EN = {
      0: 'FIRE 1',
      1: 'FIRE 1',
      2: 'FIRE 1',
      3: 'FIRE 1',
      4: 'FIRE 1',
      5: 'FIRE 2',
      6: 'FIRE 2',
      7: 'FIRE 1',
      8: 'FIRE 1',
      9: 'FIRE 1',
      10: 'FIRE 1',
      11: 'FIRE 1',
      12: 'TECH 1',
      13: 'FIRE 2',
      14: 'FIRE 2',
      15: 'FIRE 1',
      16: 'FIRE 2',
      17: 'FIRE 1',
      18: 'FIRE 1',
      19: 'FIRE 2',
      20: 'FIRE 3',
      21: 'FIRE 1',
      22: 'FIRE 3',
      23: 'FIRE 1',
      24: 'FIRE 1',
      25: 'TECH 1',
      26: 'FIRE 2',
      27: 'TECH 1',
      28: 'FIRE 1',
      29: 'FIRE 2',
      30: 'FIRE 1',
      31: 'FIRE 1',
      32: 'FIRE 3',
      33: 'FIRE 3',
      34: 'MED 1',
      35: 'MED 1',
      36: 'MED 1',
      37: 'MED 1',
      38: 'MED 1',
      39: 'MED 1',
      40: 'MED 1',
      41: 'FIRE 4',
      42: 'FIRE 2',
      43: 'MED 1',
      44: 'FIRE 3',
      45: 'FIRE 4',
      46: 'FIRE 4',
      47: 'CBRN 2',
      48: 'POL 1',
      49: 'POL 1',
      50: 'POL 1',
      51: 'POL 1',
      52: 'POL 1',
      53: 'POL 1',
      54: 'POL 1',
      55: 'POL 1',
      56: 'POL 1',
      57: 'POL 1',
      58: 'POL 1',
      59: 'POL 3',
      60: 'POL 2',
      61: 'POL 7',
      62: 'TECH 3',
      63: 'FIRE 1',
      64: 'FIRE 2',
      65: 'FIRE 2',
      66: 'TECH 1',
      67: 'MED 1',
      68: 'POL 4',
      69: 'POL 1',
      70: 'POL 3',
      71: 'POL 1',
      72: 'POL 1',
      73: 'POL 1',
      74: 'POL 1',
      75: 'FIRE 1',
      76: 'FIRE 2',
      77: 'FIRE 2',
      78: 'TECH 1',
      79: 'POL 1',
      80: 'FIRE 1',
      81: 'FIRE 1',
      82: 'TECH 1',
      83: 'FIRE 1',
      84: 'FIRE 1',
      85: 'POL 2',
      86: 'TECH 3',
      87: 'FIRE 4',
      88: 'TECH 2',
      89: 'TECH 3',
      90: 'POL 6',
      91: 'POL 7',
      92: 'POL 3',
      93: 'POL 2',
      94: 'POL 10',
      95: 'POL 5',
      96: 'POL 5',
      97: 'POL 3',
      98: 'CBRN 2',
      99: 'FIRE 4',
      100: 'MED 1',
      101: 'CBRN 2',
      102: 'FIRE 4',
      103: 'POL 2',
      104: 'POL 4',
      105: 'POL 4',
      106: 'POL 1',
      107: 'POL 1',
      108: 'MED 1',
      109: 'MED 1',
      110: 'FIRE 3',
      111: 'POL 5',
      112: 'FIRE 4',
      113: 'FIRE 2',
      114: 'FIRE 2',
      115: 'FIRE 1',
      116: 'FIRE 1',
      117: 'FIRE 1',
      118: 'FIRE 1',
      119: 'MED 1',
      120: 'TECH 3',
      121: 'POL 10',
      122: 'TECH 1',
      123: 'POL 6',
      124: 'POL 7',
      125: 'TECH 2',
      126: 'MED 1',
      127: 'FIRE 5',
      128: 'POL 1',
      129: 'POL 1',
      130: 'TECH 1',
      131: 'POL 1',
      132: 'MED 1',
      133: 'POL 1',
      134: 'POL 2',
      135: 'POL 4',
      136: 'POL 7',
      137: 'POL 4',
      138: 'FIRE 1',
      139: 'FIRE 3',
      140: 'POL 4',
      141: 'TECH 1',
      142: 'FIRE 4',
      143: 'POL 5',
      144: 'TECH 2',
      145: 'FIRE 2',
      146: 'MED 1',
      147: 'POL 1',
      148: 'TECH 1',
      149: 'FIRE 1',
      150: 'TECH TRAIN',
      151: 'TECH TRAIN',
      152: 'TECH TRAIN',
      153: 'FIRE 4',
      154: 'ABC 1',
      155: 'FIRE 4',
      156: 'MED 2',
      157: 'MED 2',
      158: 'TECH 1',
      159: 'TECH 3',
      160: 'POL 2',
      161: 'POL 5',
      162: 'TECH 2 AIRCRAFT CRASH',
      163: 'TECH 4 AIRCRAFT CRASH',
      164: 'POL 3',
      165: 'TECH WATER',
      166: 'TECH WATER',
      167: 'TECH WATER',
      168: 'TECH WATER',
      169: 'TECH WATER',
      170: 'TECH WATER',
      171: 'TECH WATER',
      172: 'TECH WATER',
      173: 'TECH 3 AIRCRAFT WATER CRASH',
      174: 'TECH 3 AIRCRAFT WATER CRASH',
      175: 'TECH 4',
      176: 'MED 1',
      177: 'MED 1',
      178: 'MED 1',
      179: 'TECH WATER',
      180: 'POL 6',
      181: 'FIRE 3',
      182: 'FIRE 2',
      183: 'FIRE 2',
      184: 'FIRE 3 SHIP',
      185: 'FIRE 2',
      186: 'FIRE 5',
      187: 'POL 4',
      188: 'TECH 4 SHIP',
      189: 'TECH 1 SHIP',
      190: 'TECH 1 SHIP',
      191: 'TECH 1 SHIP',
      192: 'TECH 2 TRAIN',
      193: 'TECH 1 ANIMAL',
      194: 'TECH 3',
      195: 'FIRE 2',
      196: 'FIRE 1',
      197: 'FIRE 1 BOAT',
      198: 'FIRE 1 BOAT',
      199: 'FIRE 1 BOAT',
      200: 'POL 4',
      201: 'POL 6',
      202: 'FIRE 5',
      203: 'FIRE 1',
      204: 'CBRN 1',
      205: 'FIRE 4',
      206: 'FIRE 1',
      207: 'POL 1',
      208: 'FIRE 4',
      209: 'FIRE 2',
      210: 'FIRE 4',
      211: 'FIRE 3',
      212: 'FIRE 4',
      213: 'FIRE 5',
      214: 'FIRE 3',
      215: 'TECH 1',
      216: 'POL 4',
      217: 'FIRE 3',
      218: 'MED 1',
      219: 'MED 1',
      220: 'MED 1',
      222: 'MED 1',
      221: 'MED 1',
      223: 'MED 1',
      224: 'POL 2',
      225: 'FIRE 2 AIRCRAFT',
      226: 'FIRE 1 AIRCRAFT',
      227: 'FIRE 2',
      228: 'FIRE 4',
      229: 'FIRE 6',
      230: 'FIRE 3',
      231: 'FIRE 3',
      232: 'TECH 2'
    };
    var DEFAULT_AAO_NL = {
      0: 'KLEINE BRAND',
      1: 'KLEINE BRAND',
      2: 'KLEINE BRAND',
      3: 'KLEINE BRAND',
      4: 'KLEINE NATUURBRAND',
      5: 'MIDDEL BRAND',
      6: 'MIDDEL BRAND',
      7: 'KLEINE BRAND',
      8: 'KLEINE BRAND',
      9: 'KLEINE BRAND',
      10: 'KLEINE BRAND',
      11: 'KLEINE BRAND',
      12: 'KLEINE HV',
      13: 'MIDDEL BRAND',
      14: 'MIDDEL NATUURBRAND',
      15: 'KLEINE NATUURBRAND',
      16: 'MIDDEL BRAND',
      17: 'KLEINE BRAND',
      18: 'KLEINE NATUURBRAND',
      19: 'KLEINE BRAND',
      20: 'GROTE BRAND',
      21: 'KLEINE BRAND',
      22: 'KLEINE BRAND',
      23: 'MIDDEL BRAND',
      24: 'KLEINE BRAND',
      25: 'KLEINE HV',
      26: 'GROTE BRAND',
      27: 'KLEINE HV',
      28: 'MIDDEL BRAND',
      29: 'GROTE BRAND',
      30: 'KLEINE HV',
      31: 'KLEINE HV',
      32: 'MIDDEL BRAND',
      33: 'KLEINE BRAND',
      34: 'MIDDEL BRAND',
      35: 'MIDDEL BRAND',
      36: 'GROTE BRAND',
      37: 'KLEINE BRAND',
      38: 'KLEINE BRAND',
      39: 'KLEINE BRAND',
      40: 'KLEINE BRAND',
      41: 'ZEER GROTE BRAND',
      42: 'ZEER GROTE BRAND',
      43: 'ZEER GROTE HV, SIS 3',
      44: 'KLEINE HV',
      45: 'A 1',
      46: 'A 1',
      47: 'A 1',
      48: 'A 1',
      49: 'A 1',
      50: 'A 1',
      51: 'A 1',
      52: 'MIDDEL BRAND',
      53: 'ZEER GROTE BRAND',
      54: 'KLEINE BRAND',
      55: 'MIDDEL BRAND',
      56: 'ZEER GROTE BRAND',
      57: 'KLEINE HV',
      58: 'KLEINE BRAND',
      59: 'ZEER GROTE BRAND',
      60: 'MIDDEL BRAND',
      61: 'KLEINE BRAND',
      62: 'GROTE BRAND',
      63: 'KLEINE BRAND',
      64: 'MIDDEL BRAND',
      65: 'KLEINE BRAND',
      66: 'KLEINE HV',
      67: 'KLEINE HV',
      68: 'KLEINE HV',
      69: 'KLEINE HV',
      70: 'P 1',
      71: 'P 1',
      72: 'P 1',
      73: 'P 1',
      74: 'P 1',
      75: 'P 1',
      76: 'MIDDEL HV, VOS 5',
      77: 'MIDDEL HV, VOS 5',
      78: 'KLEINE BRAND',
      79: 'A 1',
      80: 'A 1',
      81: 'P 1',
      82: 'MIDDEL HV',
      83: 'A 1',
      84: 'A 1',
      85: 'A 1',
      86: 'A 1, TIS 3',
      87: 'A 1',
      88: 'A 1',
      89: 'A 1',
      90: 'A 1',
      91: 'A 1',
      92: 'A 1',
      93: 'A 1',
      94: 'A 1',
      95: 'A 1',
      96: 'A 1',
      97: 'A 1',
      98: 'KLEIN 0GS',
      99: 'KLEIN 0GS',
      100: 'MIDDEL OGS',
      101: 'KLEIN 0GS',
      102: 'MIDDEL OGS, TIS 4',
      103: 'KLEINE BRAND',
      104: 'KLEINE BRAND',
      105: 'KLEINE BRAND',
      106: 'MIDDEL HV',
      107: 'P 1',
      108: 'MIDDEL HV, TIS 3',
      109: 'MIDDEL HV, TIS 3',
      110: 'KLEINE BRAND',
      111: 'MIDDEL BRAND',
      112: 'P 1',
      113: 'P 1',
      114: 'KLEINE BRAND',
      115: 'MIDDEL BRAND',
      116: 'GEPLAND',
      117: 'GEPLAND',
      118: 'GEPLAND',
      119: 'GEPLAND',
      120: 'GEPLAND',
      121: 'GEPLAND',
      122: 'P 1',
      123: 'P 1',
      124: 'P 1',
      125: 'P 1',
      126: 'KLEINE BRAND',
      127: 'GROTE BRAND',
      128: 'KLEINE NATUURBRAND',
      129: 'MIDDEL NATUURBRAND',
      130: 'MIDDEL BRAND',
      131: 'GROTE BRAND',
      132: 'KLEINE BRAND',
      133: 'KLEINE BRAND',
      134: 'KLEINE BRAND',
      135: 'KLEINE BRAND',
      136: 'KLEINE BRAND',
      137: 'B 1',
      138: 'KLEINE BRAND',
      139: 'MIDDEL NATUURBRAND',
      140: 'MIDDEL NATUURBRAND',
      141: 'GROTE NATUURBRAND',
      142: 'ZEER GROTE NATUURBRAND',
      143: 'ZEER GROTE NATUURBRAND',
      144: 'ZEER GROTE NATUURBRAND',
      145: 'ZEER GROTE NATUURBRAND',
      146: 'KLEINE BRAND',
      147: 'MIDDEL BRAND',
      148: 'KLEINE BRAND',
      149: 'KLEINE BRAND',
      150: 'P 1',
      151: 'P 1',
      152: 'P 1',
      153: 'P 1',
      154: 'P 1',
      155: 'MIDDEL HV',
      156: 'GROTE HV',
      157: 'GROTE BRAND',
      158: 'KLEINE BRAND',
      159: 'GROTE BRAND',
      160: 'KLEINE BRAND',
      161: 'A 1',
      162: 'A 1',
      163: 'P 1',
      164: 'A 1',
      165: 'KLEINE HV',
      166: 'P 1',
      167: 'P 1',
      168: 'A 1',
      169: 'KLEINE BRAND',
      170: 'KLEINE BRAND',
      171: 'KLEINE HV',
      172: 'A 1',
      173: 'P 1',
      174: 'P 1',
      175: 'KLEINE BRAND',
      176: 'A 1',
      177: 'A 1',
      178: 'P 1',
      179: 'A 1',
      180: 'KLEINE WO',
      181: 'MIDDEL HV',
      182: 'KLEINE WO',
      183: 'KLEINE HV',
      184: 'KLEINE HV',
      185: 'KLEINE WO',
      186: 'KLEINE HV',
      187: 'KLEINE HV',
      188: 'KLEINE HV',
      189: 'KLEINE HV',
      190: 'KLEINE HV',
      191: 'KLEINE HV',
      192: 'KLEINE HV',
      193: 'KLEINE HV',
      194: 'KLEINE HV',
      195: 'KLEINE HV',
      196: 'KLEINE BRAND',
      197: 'KLEINE BRAND',
      198: 'KLEINE BRAND',
      199: 'P 1',
      200: 'P 1',
      201: 'P 1',
      202: 'P 1',
      203: 'MIDDEL OGS',
      204: 'MIDDEL OGS',
      205: 'KLEINE WO',
      206: 'MIDDEL WO',
      207: 'KLEINE WO',
      208: 'MIDDEL WO',
      209: 'KLEINE WO',
      210: 'MIDDEL WO',
      211: 'GROTE WO',
      212: 'KLEINE WO',
      213: 'MIDDEL WO',
      214: 'MIDDEL NATUURBRAND',
      215: 'GROTE NATUURBRAND',
      216: 'ZEER GROTE NATUURBRAND',
      217: 'P 1',
      218: 'P 1',
      219: 'GEPLAND',
      220: 'GEPLAND',
      221: 'P 1',
      222: 'P 1',
      223: 'MIDDEL BRAND',
      224: 'KLEINE BRAND',
      225: 'A 1',
      226: 'A 1',
      227: 'P 1',
      228: 'P 1',
      229: 'ZEER GROTE BRAND',
      230: 'A 1',
      231: 'P 1',
      232: 'P 1',
      233: 'MIDDEL BRAND',
      234: 'ZEER GROTE HV, VOS 6 "CRASH"',
      235: 'P 1',
      236: 'P 1',
      237: 'KLEINE BRAND',
      238: 'KLEINE BRAND',
      239: 'A 1',
      240: 'A 1',
      241: 'KLEINE WO',
      242: 'KLEINE WO',
      243: 'P 1',
      244: 'A 1',
      245: 'GEPLAND',
      246: 'P 4',
      247: 'P 6',
      248: 'P 8',
      249: 'P 3',
      250: 'P 1',
      251: 'MIDDEL WO',
      252: 'MIDDEL WO',
      253: 'KLEINE WO',
      254: 'KLEINE BRAND',
      255: 'MIDDEL BRAND',
      256: 'P 1',
      257: 'P 1',
      258: 'KLEINE BRAND',
      259: 'MIDDEL BRAND',
      260: 'KLEINE BRAND',
      261: 'A 1',
      262: 'P 1',
      263: 'KLEINE BRAND',
      264: 'MIDDEL BRAND',
      265: 'VOS KLEIN',
      266: 'VOS KLEIN',
      267: 'VOS KLEIN',
      268: 'VOS GROOT',
      269: 'VOS GROOT',
      270: 'VOS GROOT',
      271: 'VOS KLEIN',
      272: 'VOS KLEIN',
      273: 'VOS KLEIN',
      274: 'VOS GROOT',
      275: 'VOS KLEIN',
      276: 'VOS KLEIN',
      277: 'A 1',
      278: 'A 1',
      279: 'P 1',
      280: 'KLEINE BRAND',
      281: 'GROTE BRAND',
      282: 'ZEER GROTE BRAND',
      283: 'A 1',
      284: 'P 1',
      285: 'KLEINE BRAND',
      286: 'KLEINE HV',
      287: 'KLEINE BRAND',
      288: 'KLEINE BRAND',
      289: 'MIDDEL BRAND',
      290: 'GROTE BRAND',
      291: 'ZEER GROTE BRAND',
      292: 'GROTE HV',
      293: 'GROTE HV',
      294: 'P 1',
      295: 'P 1',
      296: 'KLEINE BRAND',
      297: 'MIDDEL BRAND',
      298: 'GROTE BRAND',
      299: 'KLEINE BRAND',
      300: 'MIDDEL BRAND',
      301: 'P 1',
      302: 'KLEINE BRAND',
      303: 'MIDDEL BRAND',
      304: 'GROTE BRAND',
      305: 'GROTE HV',
      306: 'GROTE HV',
      307: 'GROTE HV',
      308: 'ZEER GROTE NATUURBRAND',
      309: 'ZEER GROTE NATUURBRAND',
      310: 'A 2',
      311: 'A 1',
      312: 'GROTE OGS, TIS 5',
      313: 'KLEINE BRAND, TREIN',
      314: 'MIDDEL BRAND, TREIN',
      315: 'GROTE BRAND, TREIN',
      316: 'P 2',
      317: 'P 4',
      318: 'KLEINE BRAND, SCHIP',
      319: 'MIDDEL BRAND, SCHIP',
      320: 'GROTE BRAND, SCHIP',
      321: 'KLEINE BRAND',
      322: 'MIDDEL BRAND',
      323: 'A 1',
      324: 'A 2',
      325: 'A 2',
      326: 'ZEER GROOTE BRAND',
      327: 'EXTREEM GROOTE BRAND',
      328: 'KLEINE HV',
      329: 'P 1',
      330: 'P 5',
      331: 'P 2',
      332: 'P 2',
      333: 'P 3',
      334: 'KLEINE BRAND',
      335: 'MIDDEL BRAND',
      336: 'GROTE BRAND',
      337: 'P 1',
      338: 'P 1',
      339: 'KLEINE HV',
      340: 'MIDDEL HV',
      341: 'KLEINE BRAND',
      342: 'KLEINE BRAND',
      343: 'KLEINE BRAND',
      344: 'OGS 1',
      345: 'OGS 2',
      346: 'OGS 4',
      347: 'OGS 4',
      348: 'MIDDEL WO',
      349: 'GROTE WO',
      350: 'P 3',
      351: 'P 2',
      352: 'KLEINE BRAND',
      353: 'MIDDEL BRAND',
      354: 'GROTE BRAND',
      355: 'GROTE NATUURBRAND',
      356: 'ZEER GROTE NATUURBRAND',
      357: 'ZEER GROTE NATUURBRAND',
      358: 'A 1',
      359: 'A 1',
      360: 'KLEINE BRAND',
      361: 'KLEINE BRAND',
      362: 'MIDDEL BRAND',
      363: 'KLEINE BRAND, SCHIP',
      364: 'MIDDEL BRAND, SCHIP',
      365: 'GROTE BRAND, SCHIP',
      366: 'P 1',
      367: 'P 1',
      368: 'P 2',
      369: 'P 2, A 1',
      370: 'KLEINE HV , A 1',
      371: 'KLEINE WO',
      372: 'KLEINE BRAND',
      373: 'A 1',
      374: 'P 1',
      375: 'KLEINE HV',
      376: 'GROTE WO',
      377: 'GROTE WO',
      378: 'OGS 1',
      379: 'OGS 2',
      380: 'A 1',
      381: 'A 1',
      382: 'A 1',
      383: 'KLEINE BRAND',
      384: 'MIDDEL BRAND',
      385: 'GROTE BRAND',
      386: 'ZEER GROTE BRAND',
      387: 'A 1',
      388: 'A 1',
      389: 'KLEINE HV'
    };

    // Alle Einsatz-IDs mit Stichwort-Zuweisung
    I18n.translations.de.lssm.missionKeyword = DEFAULT_AAO_DE;
    I18n.translations.en.lssm.missionKeyword = DEFAULT_AAO_EN;
    I18n.translations.nl.lssm.missionKeyword = DEFAULT_AAO_NL;

    var defaultAao;
    if (I18n.locale === 'de')
      defaultAao = DEFAULT_AAO_DE;
    else if (I18n.locale === 'en')
      defaultAao = DEFAULT_AAO_EN;
    else if (I18n.locale === 'nl')
      defaultAao = DEFAULT_AAO_NL;
    else
      defaultAao = DEFAULT_AAO_DE;


    $.each(defaultAao, function(key, val) {
      var tmpObject = {
        ['missionKeyword-' + key]: {
          "default": val,
          "ui": {
            "label": I18n.t('lssm.missionKeywordDefaults.keywords.' + key) + " (ID " + key + ")",
            "type": "text",
            "description": ""
          }
        }
      };

      $.extend(managedSettings.settings, tmpObject);

    });

    lssm.managedSettings.register(managedSettings);
  }

  function getSetting(setting) {
    return lssm.managedSettings.getSetting(LSS_MISSIONKEYWORD_STORAGE, setting);
  }

  function missionKeyword() {
    // Stichwort Element
    var titleStichwort = $('#missionH1');
    // Anzahl Patientenbalken
    var anzahlPatients = $(".patient_progress").length;
    var aaoText = '';

    // Einsatz-ID aus Hilfe-Link
    var missionId = $('#mission_help').attr('href').split("/").pop().replace(/\?.*/, '');

    // aao_text = I18n.t('lssm.missionKeyword.'+missionId);
    aaoText = getSetting('missionKeyword-' + missionId);
    if (titleStichwort.text().toLowerCase().includes(I18n.t('lssm.missionKeywordDefaults.bmaLong').toLowerCase()))
    // Wenn BMA im Titel, setze Stichwort mit BMA am Ende
    {
      aaoText = aaoText + ' ' + I18n.t('lssm.missionKeywordDefaults.bma');
    }
    var additionalAaoText = '';
    if (anzahlPatients > 0) {
      if (I18n.locale === 'de') {

        // Wenn 1+ Patienten vorhanden, modifiziere Stichwort zu XY PERSON

        if (aaoText.match(/B [0-9]/ig)) {
          aaoText = aaoText + ' PERSON';
        } else if (aaoText.match(/FEU [0-9]|TH [0-9]/ig)) {
          var n = aaoText.search(/[0-9]/i);
          if (n > 0) {
            aaoText = [a.slice(0, n + 1), ' Y', a.slice(n + 1)].join('');
          }

        }

        if (!aaoText.match(I18n.t('lssm.missionKeywordDefaults.rd'))) {
          additionalAaoText = '<span class="label label-warning">';

          if (I18n.t('lssm.missionKeywordDefaults.rd') === 'RD') {
            // Füge die RD-Kennung hinzu, wenn der Einsatz KEIN RD-Einsatz ist
            if (anzahlPatients > 1 && anzahlPatients < 4)
              additionalAaoText += 'RD 3';
            else if (anzahlPatients >= 4 && anzahlPatients < 6)
              additionalAaoText += 'RD 4';
            else if (anzahlPatients >= 6 && anzahlPatients < 10)
              additionalAaoText += 'RD 5';
            else if (anzahlPatients >= 10 && anzahlPatients < 16)
              additionalAaoText += 'MANV 10-15';
            else if (anzahlPatients >= 16 && anzahlPatients < 26)
              additionalAaoText += 'MANV 16-25';
            else if (anzahlPatients >= 26 && anzahlPatients < 51)
              additionalAaoText += 'MANV 26-50';
            else if (anzahlPatients >= 51 && anzahlPatients < 101)
              additionalAaoText += 'MANV 51-100';
            else if (anzahlPatients >= 101)
              additionalAaoText += 'MANV 100+';
          }

          if (I18n.t('lssm.missionKeywordDefaults.rd') === 'NOTF') {
            // Füge die RD-Kennung hinzu, wenn der Einsatz KEIN RD-Einsatz ist
            if (anzahlPatients > 5 && anzahlPatients < 11)
              additionalAaoText += 'MANV10';
            else if (anzahlPatients >= 11 && anzahlPatients < 26)
              additionalAaoText += 'MANV25';
            else if (anzahlPatients >= 26 && anzahlPatients < 51)
              additionalAaoText += 'MANV50';
            else if (anzahlPatients >= 51)
              additionalAaoText += 'MANV50+';
          }
          additionalAaoText += '</span>';
        }
      } else if (I18n.locale === 'en') {
        if (!aaoText.match(I18n.t('lssm.missionKeywordDefaults.rd'))) {
          additionalAaoText = '<span class="label label-warning">';
          if (anzahlPatients >= 10 && anzahlPatients < 21)
            additionalAaoText += 'MED CODE 10';
          else if (anzahlPatients >= 21 && anzahlPatients < 30)
            additionalAaoText += 'MED CODE 20';
          else if (anzahlPatients >= 30 && anzahlPatients < 40)
            additionalAaoText += 'MED CODE 30';
          else if (anzahlPatients >= 40 && anzahlPatients < 50)
            additionalAaoText += 'MED CODE 40';
          else if (anzahlPatients >= 50)
            additionalAaoText += 'MED CODE 50';

          additionalAaoText += '</span>';
        }
      } else if (I18n.locale === 'nl') {
        if (!aaoText.match(I18n.t('lssm.missionKeywordDefaults.rd'))) {
          additionalAaoText = '<span class="label label-warning">';
          if (anzahlPatients >= 10 && anzahlPatients < 21)
            additionalAaoText += 'A1 CODE 10';
          else if (anzahlPatients >= 21 && anzahlPatients < 30)
            additionalAaoText += 'A1 CODE 20';
          else if (anzahlPatients >= 30 && anzahlPatients < 40)
            additionalAaoText += 'A1 CODE 30';
          else if (anzahlPatients >= 40 && anzahlPatients < 50)
            additionalAaoText += 'A1 CODE 40';
          else if (anzahlPatients >= 50)
            additionalAaoText += 'A1 CODE 50';

          additionalAaoText += '</span>';
        }
      }
    }
    var label = 'label-info';

    // Setze Label Farben
    if (aaoText.match(I18n.t('lssm.missionKeywordDefaults.rd')) ||
      aaoText.match(I18n.t('lssm.missionKeywordDefaults.ktp'))) {
      label = 'label-warning';
    }
    if (aaoText.match(I18n.t('lssm.missionKeywordDefaults.fw')) ||
      aaoText.match(I18n.t('lssm.missionKeywordDefaults.thl')) ||
      aaoText.match(I18n.t('lssm.missionKeywordDefaults.abc'))) {
      label = 'label-danger';
    }
    if (aaoText.match(I18n.t('lssm.missionKeywordDefaults.pol')) ||
      aaoText.match(I18n.t('lssm.missionKeywordDefaults.bp')) ||
      aaoText.match(I18n.t('lssm.missionKeywordDefaults.sek')) ||
      aaoText.match(I18n.t('lssm.missionKeywordDefaults.mek'))) {
      label = 'label-success';
    }
    if (aaoText.match(I18n.t('lssm.missionKeywordDefaults.thw'))) {
      label = 'label-primary';
    }

    // Füge Label hinzu
    if (titleStichwort !== null) {
      titleStichwort.append('<span class="label ' + label + '">' + aaoText + '</span>' + additionalAaoText);
    }
  }

  setSettings();

  // Only execute this script in the alert iframe.
  // Identify the iframe with mission_help link.
  var missionHelp = $('#mission_help');
  if (missionHelp.length > 0) {
    missionKeyword();
  }
})();
